server:
  port: 8888

spring:
  application:
    name: springcloud-service-08-config
  cloud:
    config:
      server:
        git:
          uri:
          search-paths:
          username:
          password: