eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        instance-id: springcloud-service-02-goods-9200
        lease-expiration-duration-in-seconds: 10
        lease-renewal-interval-in-seconds: 2
        prefer-ip-address: true
server:
    port: 9200
    servlet:
        context-path: /service
spring:
    application:
        name: springcloud-service-02-goods
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 214626
        url: jdbc:mysql://localhost:3306/goodsdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
        username: root
